[package]
name = "blockscan"
description = "A package for interacting with the Blocscan API (mainly chat)."
license = "BSD-3-Clause"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
